baseURL = 'https://somnathdas.github.io/'
languageCode = 'en-us'
title = "Somnath Das"
theme = 'nostyleplease'
enableRobotsTXT = true

[markup]
[markup.highlight]
style = 'solarized-dark'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  favicon = "/favicon.ico"