baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Somnath Das"
theme = 'nostyleplease'

[markup]
[markup.highlight]
style = 'solarized-dark'

[caches]
  [caches.images]
    dir = ':cacheDir/images'